before:
  hooks:
    - go mod tidy
builds:
  - binary: gollm
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: gollm
    homepage: "https://github.com/chavdim/gollm"
    tap:
      owner: chavdim
      name: homebrew-taps
    commit_author:
      name: chavdim
      email: chavdardim90@gmail.com

checksum:
  name_template: 'checksums.txt'
